# Generated by Django 6.0 on 2025-12-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='babh_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='БАБХ номер'),
        ),
    ]
